export { default as Header } from './header/Header.jsx'
export { default as Home } from './home/Home.jsx'
export { default as Skills } from './skills/Skills.jsx'
export { default as Experience } from './experience/Experience.jsx'
export { default as Contact } from './contact/Contact.jsx'
export { default as Projects } from './projects/Projects.jsx'
